n = input('Digite algo: ')

print('Tipo:')
print(type(n))
print('Númerico:')
print(n.isnumeric())
print('Alfabetico:')
print(n.isalpha())
print('Alfanúmerico:')
print(n.isalnum())
print('Somente Letras em Maiusculas:')
print(n.isupper())
print('Primeira letra Maiuscula:')
print(n.istitle())